import test from 'node:test';import assert from 'node:assert/strict';import {once} from 'node:events';
import {createStudioServer,analyzeAudio,wavDuration} from '../server.mjs';import {encodeWav} from '../audio.mjs';
const audio=async()=>Buffer.from(await encodeWav(new Float32Array(16000*6)).arrayBuffer());
const withServer=async(options,run)=>{const server=createStudioServer(options);server.listen(0,'127.0.0.1');await once(server,'listening');try{await run(`http://127.0.0.1:${server.address().port}`);}finally{await new Promise(resolve=>server.close(resolve));}};
test('unconfigured service exposes status but cannot charge provider',()=>withServer({apiKey:'',token:''},async base=>{assert.equal((await(await fetch(base+'/api/health')).json()).ready,false);assert.equal((await fetch(base+'/api/analyze',{method:'POST'})).status,503);assert.equal((await fetch(base+'/.env')).status,404);assert.equal((await fetch(base+'/server.mjs')).status,404);}));
test('analysis rejects missing auth and unauthorized origins',()=>withServer({apiKey:'test-not-a-real-key',token:'test-private-token',analyze:()=>{throw Error('should not run');}},async base=>{assert.equal((await fetch(base+'/api/analyze',{method:'POST'})).status,401);assert.equal((await fetch(base+'/api/health',{headers:{Origin:'https://untrusted.example'}})).status,403);}));
test('authorized audio reaches analyzer, no credentials returned',()=>withServer({apiKey:'test-not-a-real-key',token:'test-private-token',analyze:async bytes=>({duration:wavDuration(bytes),words:[],plan:{scenes:[]}})},async base=>{const response=await fetch(base+'/api/analyze',{method:'POST',headers:{Authorization:'Bearer test-private-token','Content-Type':'audio/wav'},body:await audio()});assert.equal(response.status,200);const text=await response.text();assert.match(text,/"duration":6/);assert.ok(!text.includes('key'));}));
test('provider integration asks for word timings and a strict plan',async()=>{let calls=0;const result=await analyzeAudio(await audio(),{apiKey:'test-only',fetchImpl:async(url,options)=>{calls++;if(url.endsWith('transcriptions')){assert.equal(options.body.get('model'),'whisper-1');assert.equal(options.body.get('timestamp_granularities[]'),'word');return Response.json({words:[{word:'Bonjour',start:0,end:1}]});}const body=JSON.parse(options.body);assert.equal(body.store,false);assert.equal(body.text.format.strict,true);return Response.json({status:'completed',output:[{content:[{type:'output_text',text:'{"scenes":[]}'}]}]});}});assert.equal(calls,2);assert.equal(result.words[0].word,'Bonjour');});
test('provider refusal and invalid timestamps cannot generate motions',async()=>{await assert.rejects(analyzeAudio(await audio(),{apiKey:'test',fetchImpl:async()=>Response.json({words:[{word:'x',start:0,end:100}]})}));});
